twitter-to-kafka-service:
    twitter-keywords:
        - Java
        - Microservices
        - Spring
        - Kafka
        - Elasticsearch
    welcome-message: "OLA MUNDO CRUEL"
    enable-mock-tweets: true
    mock-min-tweet-length: 5
    mock-max-tweet-length: 15
    mock-sleep-ms: 10000

retry-config:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    max-attemps: 3
    sleep-time-ms: 2000

kafka-config:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    schema-registry-url-key:
    schema-registry-url:
    topic-name:
    topic-names-to-create:
    num-of-partitions:
    replication-factor: